import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
#Define PIN 17 as OUT GPIO (Servomotor)
GPIO.setup(17, GPIO.OUT)
#Define Name and PWM (50Hz)for PIN 17,
servo = GPIO.PWM(17,50)


print ("180 degrees")
servo.start(12.5) # Initialisierung
time.sleep(5)
print ("171 degrees")
servo.ChangeDutyCycle(12)
time.sleep(5)
print ("162 degrees")
servo.ChangeDutyCycle(11.5)
time.sleep(5)
print ("153 degrees")
servo.ChangeDutyCycle(11)
time.sleep(5)
print ("144 degrees")
servo.ChangeDutyCycle(10.5)
time.sleep(5)
print ("135 degrees")
servo.ChangeDutyCycle(10)
time.sleep(5)
print ("126 degrees")
servo.ChangeDutyCycle(9.5)
time.sleep(5)
print ("117 degrees")
servo.ChangeDutyCycle(9.0)
time.sleep(5)
print ("108 degrees")
servo.ChangeDutyCycle(8.5)
time.sleep(5)
print ("99 degrees")
servo.ChangeDutyCycle(8)
time.sleep(5)
print ("90 degrees")
servo.ChangeDutyCycle(7.5)
time.sleep(5)
print ("81 degrees")
servo.ChangeDutyCycle(7)
time.sleep(5)
print ("72 degrees")
servo.ChangeDutyCycle(6.5)
time.sleep(5)
print ("63 degrees")
servo.ChangeDutyCycle(6)
time.sleep(5)
print ("54 degrees")
servo.ChangeDutyCycle(5.5)
time.sleep(5)
print ("45 degrees")
servo.ChangeDutyCycle(5)
time.sleep(5)
print ("36 degrees")
servo.ChangeDutyCycle(4.5)
time.sleep(5)
print ("27 degrees")
servo.ChangeDutyCycle(4)
time.sleep(5)
print ("18 degrees")
servo.ChangeDutyCycle(3.5)
time.sleep(5)
print ("9 degrees")
servo.ChangeDutyCycle(3)
time.sleep(5)
print ("0 degrees")
servo.ChangeDutyCycle(0)
time.sleep(5)
print ("Turning back to 180 degrees (Slider out of tray)")
servo.ChangeDutyCycle(12.5)
time.sleep(5.0)